name: goreleaser

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
jobs:
  call-workflow-passing-data:
    uses: Vioneta/github/.github/workflows/go_release.yml@main
    with:
      project-name: VionetaOS
      file-name: vionetaos
    secrets:
      # GoogleID: ${{ secrets.GoogleID }}
      # GoogleSecret: ${{ secrets.GoogleSecret }}
      DropboxKey: ${{ secrets.DropboxKey }}
      DropboxSecret: ${{ secrets.DropboxSecret }}
      # OneDriveID: ${{ secrets.OneDriveID }}
      # OneDriveSecret: ${{ secrets.OneDriveSecret }}
      # OneDrivePublic: ${{ secrets.OneDrivePublic }}
      # OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
      # OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
